// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZRoRxwDM1U7wTD0I7lcMJrEiCyUKnkFk',
    appId: '1:363624634789:web:d1cb2fb5ba56f59407304c',
    messagingSenderId: '363624634789',
    projectId: 'notepad-aada1',
    authDomain: 'notepad-aada1.firebaseapp.com',
    storageBucket: 'notepad-aada1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLrW9x3xk0UmrPWZSGXkR_z8ZsaBveKRw',
    appId: '1:363624634789:android:4ab33022ac68380007304c',
    messagingSenderId: '363624634789',
    projectId: 'notepad-aada1',
    storageBucket: 'notepad-aada1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2bFgWS6FE3z6vdQh2W5ooDZSFVSO0StE',
    appId: '1:363624634789:ios:9ca23bbfc2ae978907304c',
    messagingSenderId: '363624634789',
    projectId: 'notepad-aada1',
    storageBucket: 'notepad-aada1.appspot.com',
    iosClientId: '363624634789-bb3v4m3ej95s7dv436a88sn4cuiehb3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepad',
  );
}
